//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlimWaist.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlimWaist.Languages.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added successfully.
        /// </summary>
        public static string Addedsuccessfully {
            get {
                return ResourceManager.GetString("Addedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add food to meal cart.
        /// </summary>
        public static string Addfoodtomealcart {
            get {
                return ResourceManager.GetString("Addfoodtomealcart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new food.
        /// </summary>
        public static string Addnewfood {
            get {
                return ResourceManager.GetString("Addnewfood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add quantity.
        /// </summary>
        public static string Addquantity {
            get {
                return ResourceManager.GetString("Addquantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body activity.
        /// </summary>
        public static string Bodyactivity {
            get {
                return ResourceManager.GetString("Bodyactivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body mass analysis.
        /// </summary>
        public static string Bodymassanalysis {
            get {
                return ResourceManager.GetString("Bodymassanalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body mass index (BMI).
        /// </summary>
        public static string Bodymassindex {
            get {
                return ResourceManager.GetString("Bodymassindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        public static string Breakfast {
            get {
                return ResourceManager.GetString("Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        public static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories calculated for each 100 gm.
        /// </summary>
        public static string Caloriescalculatedforeach100gm {
            get {
                return ResourceManager.GetString("Caloriescalculatedforeach100gm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbohydrates.
        /// </summary>
        public static string Carbohydrates {
            get {
                return ResourceManager.GetString("Carbohydrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        public static string Clearall {
            get {
                return ResourceManager.GetString("Clearall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumed calories.
        /// </summary>
        public static string Consumedcalories {
            get {
                return ResourceManager.GetString("Consumedcalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Contactus {
            get {
                return ResourceManager.GetString("Contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create one day plan.
        /// </summary>
        public static string Createonedayplan {
            get {
                return ResourceManager.GetString("Createonedayplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current regieme.
        /// </summary>
        public static string Currentregieme {
            get {
                return ResourceManager.GetString("Currentregieme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current weight.
        /// </summary>
        public static string Currentweight {
            get {
                return ResourceManager.GetString("Currentweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day calories.
        /// </summary>
        public static string Daycalories {
            get {
                return ResourceManager.GetString("Daycalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully.
        /// </summary>
        public static string Deletedsuccessfully {
            get {
                return ResourceManager.GetString("Deletedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diets.
        /// </summary>
        public static string Diets {
            get {
                return ResourceManager.GetString("Diets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet type.
        /// </summary>
        public static string Diettype {
            get {
                return ResourceManager.GetString("Diettype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        public static string Dinner {
            get {
                return ResourceManager.GetString("Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like the app?.
        /// </summary>
        public static string Doyouliketheapp {
            get {
                return ResourceManager.GetString("Doyouliketheapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit membership.
        /// </summary>
        public static string Editmembership {
            get {
                return ResourceManager.GetString("Editmembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string Editprofile {
            get {
                return ResourceManager.GetString("Editprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fats.
        /// </summary>
        public static string Fats {
            get {
                return ResourceManager.GetString("Fats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibers.
        /// </summary>
        public static string Fibers {
            get {
                return ResourceManager.GetString("Fibers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food name.
        /// </summary>
        public static string Foodname {
            get {
                return ResourceManager.GetString("Foodname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foods.
        /// </summary>
        public static string Foods {
            get {
                return ResourceManager.GetString("Foods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grams.
        /// </summary>
        public static string Grams {
            get {
                return ResourceManager.GetString("Grams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal weight.
        /// </summary>
        public static string Idealweight {
            get {
                return ResourceManager.GetString("Idealweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keto diet is a low-carb, high-fat diet that helps the body enter ketosis, where it burns fat for energy instead of carbs. It includes foods like meat, eggs, cheese, oils, and non-starchy vegetables, while avoiding bread, sugar, pasta, and most fruits. Benefits include weight loss and steady energy. Some may experience side effects like fatigue or headache at first..
        /// </summary>
        public static string Ketodescription {
            get {
                return ResourceManager.GetString("Ketodescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keto diet.
        /// </summary>
        public static string Ketodiet {
            get {
                return ResourceManager.GetString("Ketodiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginPageButtonLogin {
            get {
                return ResourceManager.GetString("LoginPageButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save email and password.
        /// </summary>
        public static string LoginPageCheckBox {
            get {
                return ResourceManager.GetString("LoginPageCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register for new.
        /// </summary>
        public static string LoginPageLabelAddNewMembership {
            get {
                return ResourceManager.GetString("LoginPageLabelAddNewMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t have membership .
        /// </summary>
        public static string LoginPageLabelHaveNoMembership {
            get {
                return ResourceManager.GetString("LoginPageLabelHaveNoMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy way for weight loss.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A low-calorie diet limits daily calorie intake, typically between 1200–1800 calories, to support weight loss and improve overall health. It emphasizes nutrient-rich foods like vegetables, fruits, lean proteins, and whole grains, while reducing sugars, fried foods, and processed snacks. This diet helps create a calorie deficit, which encourages the body to burn stored fat. For best results, it should be balanced to provide essential nutrients and may be adjusted based on age, activity level, and health goals [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Lowcarbdescription {
            get {
                return ResourceManager.GetString("Lowcarbdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low carb diet.
        /// </summary>
        public static string Lowcarbdiet {
            get {
                return ResourceManager.GetString("Lowcarbdiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        public static string Lunch {
            get {
                return ResourceManager.GetString("Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal.
        /// </summary>
        public static string Meal {
            get {
                return ResourceManager.GetString("Meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal calories.
        /// </summary>
        public static string Mealcalories {
            get {
                return ResourceManager.GetString("Mealcalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal components.
        /// </summary>
        public static string Mealcomponents {
            get {
                return ResourceManager.GetString("Mealcomponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mealname.
        /// </summary>
        public static string Mealname {
            get {
                return ResourceManager.GetString("Mealname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal name exists before.
        /// </summary>
        public static string Mealnameexistsbefore {
            get {
                return ResourceManager.GetString("Mealnameexistsbefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal type.
        /// </summary>
        public static string Mealtype {
            get {
                return ResourceManager.GetString("Mealtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified weight.
        /// </summary>
        public static string Modifiedweight {
            get {
                return ResourceManager.GetString("Modifiedweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My meals.
        /// </summary>
        public static string Mymeals {
            get {
                return ResourceManager.GetString("Mymeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New membership.
        /// </summary>
        public static string Newmembership {
            get {
                return ResourceManager.GetString("Newmembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No diet selected.
        /// </summary>
        public static string Nodietselected {
            get {
                return ResourceManager.GetString("Nodietselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No food by this name !.
        /// </summary>
        public static string Nofoodbythisname {
            get {
                return ResourceManager.GetString("Nofoodbythisname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No foods in the cart !.
        /// </summary>
        public static string Nofoodsinthecart {
            get {
                return ResourceManager.GetString("Nofoodsinthecart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items to be added !.
        /// </summary>
        public static string Noitemstobeadded {
            get {
                return ResourceManager.GetString("Noitemstobeadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No regieme till now !.
        /// </summary>
        public static string Noregiemetillnow {
            get {
                return ResourceManager.GetString("Noregiemetillnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obesity degree.
        /// </summary>
        public static string Obesitydegree {
            get {
                return ResourceManager.GetString("Obesitydegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare your favorite meal.
        /// </summary>
        public static string Prepareyourfavoritemeal {
            get {
                return ResourceManager.GetString("Prepareyourfavoritemeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protiens.
        /// </summary>
        public static string Protiens {
            get {
                return ResourceManager.GetString("Protiens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string RegexValidationMessage {
            get {
                return ResourceManager.GetString("RegexValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining calories.
        /// </summary>
        public static string Remainingcalories {
            get {
                return ResourceManager.GetString("Remainingcalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Body Activity.
        /// </summary>
        public static string SelectBodyActivity {
            get {
                return ResourceManager.GetString("SelectBodyActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select diet type.
        /// </summary>
        public static string Selectdiettype {
            get {
                return ResourceManager.GetString("Selectdiettype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Serving Size Diet involves controlling portion sizes of different food groups to maintain a balanced diet and avoid overeating. Each food group has a defined serving size, such as 30g of protein (e.g., chicken), 1 cup of vegetables, or ½ cup of grains. This system helps regulate calorie intake while ensuring the body gets the necessary nutrients. It&apos;s commonly used for weight management, promoting healthy eating habits, and creating sustainable, balanced meals..
        /// </summary>
        public static string Servingsizedescription {
            get {
                return ResourceManager.GetString("Servingsizedescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving size diet.
        /// </summary>
        public static string Servingsizediet {
            get {
                return ResourceManager.GetString("Servingsizediet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default for next days.
        /// </summary>
        public static string Setasdefaultfornextdays {
            get {
                return ResourceManager.GetString("Setasdefaultfornextdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string Showall {
            get {
                return ResourceManager.GetString("Showall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slim waste.
        /// </summary>
        public static string Slimwaste {
            get {
                return ResourceManager.GetString("Slimwaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start regieme.
        /// </summary>
        public static string Startregieme {
            get {
                return ResourceManager.GetString("Startregieme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted weight.
        /// </summary>
        public static string Targetedweight {
            get {
                return ResourceManager.GetString("Targetedweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        public static string Termsandconditions {
            get {
                return ResourceManager.GetString("Termsandconditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total calories.
        /// </summary>
        public static string Totalcalories {
            get {
                return ResourceManager.GetString("Totalcalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total carbohydrates.
        /// </summary>
        public static string Totalcarbohydrates {
            get {
                return ResourceManager.GetString("Totalcarbohydrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total energy.
        /// </summary>
        public static string Totalenergy {
            get {
                return ResourceManager.GetString("Totalenergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total fats.
        /// </summary>
        public static string Totalfats {
            get {
                return ResourceManager.GetString("Totalfats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total fibers.
        /// </summary>
        public static string Totalfibers {
            get {
                return ResourceManager.GetString("Totalfibers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total protiens.
        /// </summary>
        public static string Totalprotiens {
            get {
                return ResourceManager.GetString("Totalprotiens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully.
        /// </summary>
        public static string Updatedsuccessfully {
            get {
                return ResourceManager.GetString("Updatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password.
        /// </summary>
        public static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.5.1.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist circumference.
        /// </summary>
        public static string Waistcircumference {
            get {
                return ResourceManager.GetString("Waistcircumference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist circumference evaluation.
        /// </summary>
        public static string Waistcircumferenceevaluation {
            get {
                return ResourceManager.GetString("Waistcircumferenceevaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back.
        /// </summary>
        public static string Welcomeback {
            get {
                return ResourceManager.GetString("Welcomeback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write food name.
        /// </summary>
        public static string Writefoodname {
            get {
                return ResourceManager.GetString("Writefoodname", resourceCulture);
            }
        }
    }
}
